apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shopper
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: payment-service
          image: payment-service:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: payment-service-config
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef: { name: payment-db-secret, key: DB_NAME }
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef: { name: payment-db-secret, key: DB_USERNAME }
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: payment-db-secret, key: DB_PASSWORD }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8080 }
            initialDelaySeconds: 70
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests: { cpu: 200m, memory: 384Mi }
            limits: { memory: 768Mi }
