apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: shopper
  labels:
    app: keycloak-db
spec:
  type: ClusterIP
  selector:
    app: keycloak-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
