apiVersion: v1
kind: ConfigMap
metadata:
  name: shopper-config
  namespace: shopper
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  PAYMENT_EVENTS_TOPIC: payment-events
  KAFKA_CONSUMER_GROUP: order-service