apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: shopper
type: Opaque
stringData:
  DB_NAME: order_service
  DB_USERNAME: order_service
  DB_PASSWORD: order_service
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: shopper
type: Opaque
stringData:
  DB_NAME: payment_db
  DB_USERNAME: admin
  DB_PASSWORD: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: shopper
type: Opaque
stringData:
  DB_NAME: shopper
  DB_USERNAME: shopper
  DB_PASSWORD: shopper
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: shopper
type: Opaque
stringData:
  DB_NAME: keycloak
  DB_USERNAME: keycloak
  DB_PASSWORD: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: shopper
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  AUTH_SERVICE_CLIENT_SECRET: local-authentication-service-secret
