apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: shopper
type: Opaque
stringData:
  DB_NAME: order_service
  DB_USERNAME: order_service
  DB_PASSWORD: order_service
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: shopper
type: Opaque
stringData:
  DB_NAME: payment_service
  DB_USERNAME: payment_service
  DB_PASSWORD: payment_service