apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: shopper
  labels:
    app: payment-db
spec:
  type: ClusterIP
  selector:
    app: payment-db
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017