apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-service-config
  namespace: shopper
data:
  KEYCLOAK_SERVER_URL: http://keycloak:8080
  KEYCLOAK_REALM: shopper
  KEYCLOAK_CLIENT_ID: authentication-service
  USER_SERVICE_URL: http://user-service:8080
  HTTP_CONNECT_TIMEOUT: 3s
  HTTP_READ_TIMEOUT: 10s
