apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: shopper
  labels:
    app: authentication-service
spec:
  type: ClusterIP
  selector:
    app: authentication-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
